name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      AUTH_COOKIE_SECRET: ${{ secrets.AUTH_COOKIE_SECRET }}
      MAGIC_LINK_SECRET: ${{ secrets.MAGIC_LINK_SECRET }}
      ORIGIN: ${{ secrets.ORIGIN }}
      BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_STATIC_BUCKET: ${{ secrets.S3_STATIC_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Create .env file from secrets
        run: |
          echo "AUTH_COOKIE_SECRET=$AUTH_COOKIE_SECRET" > .env
          echo "MAGIC_LINK_SECRET=$MAGIC_LINK_SECRET" >> .env
          echo "ORIGIN=$ORIGIN" >> .env
          echo "BREVO_API_KEY=$BREVO_API_KEY" >> .env
          echo "AWS_REGION=$AWS_REGION" >> .env
          echo "S3_STATIC_BUCKET=$S3_STATIC_BUCKET" >> .env
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY " >> .env

      # - name: Store log files
      #   run: |
      #     mkdir -p logs
      #     ls -al > logs/ls.txt
      #     cat .env > logs/env.txt

      # - name: Run dev server
      #   run: |
      #     mkdir -p logs
      #     npm run dev > logs/server.log &

      # - name: Check server health
      #   run: |
      #     for i in {1..30}; do
      #       if curl -f -v http://localhost:3000; then
      #         echo "Server is up and running"
      #         exit 0
      #       fi
      #       echo "Server not ready yet"
      #       sleep 1
      #     done
      #     echo "Server did not start within 30 seconds"
      #     exit 1

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: artifacts
          path: |
            playwright-report/
            logs/
          retention-days: 30
